function initializeDisplayed(db) {

    db.serialize(() => {
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (1, "State museum of Namibia", "Keetmanshoop, Namibia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (2, "Caves of Lascaux", "Montignac, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (3, "National Museum of Anthropology", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (4, "Algerian section of the Sahara Desert", "Algeria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (5, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (6, "National Museum", "Riyad, Saudi Arabia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (7, "MET ", "New York City, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (8, "None", "England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (9, "National Gallery of Australia", "Canberra, Australia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (10, "Princeton Universtiy of Art Museum", "Princeton, New Jersey")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (11, "Dept. of Anthropology Univ. of Auckland", "Auckland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (12, "Iraq", "Warka, Iraq")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (13, "Egptian Museum", "Cairo, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (14, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (15, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (16, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (17, "None", "Cairo, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (18, "Museum of Fine Arts", "Boston, Massachusettes")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (19, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (20, "None", "Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (21, "None", "Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (22, "Neues Museum, Staatliche Museen zu Berlin", "Berlin, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (23, "the Egyptian Museum", "Cairo, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (24, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (25, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (26, "None", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (27, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (28, "Acropolis Museum", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (29, "National Etruscan Museum of Villa Giulia", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (30, "Iran", "Shiraz, Iran")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (31, "National Etruscan Museum", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (32, "Tarquinia national museum", "Tarquinia, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (33, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (34, "Museo Archeologico Nazionale di Napoli", "Naples, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (35, "None", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (36, "National Archaeological Museum", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (37, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (38, "Pergamon Museum", "Berlin, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (39, "None", "Pompeii, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (40, "Museo Archeologico Nazionale di Napoli", "Naples, NItaly")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (41, "Palazzo Massimo alle Terme", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (42, "Palazzo Torionia", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (43, "Braccio Nuovo Vatican Museums", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (44, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (45, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (46, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (47, "Palazzo Altemps in National Museum ", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (48, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (49, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (50, "Osterreichische Nationalbibliothek", "Vienna, Austria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (51, "None", "Ravenna, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (52, "None", "Istanbul, Turkey")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (53, "Chateau de Saint-Germain-en-Laye", "Saint-Germain-en-Laye, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (54, "St. Catherine's Monastery", "Sinai, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (55, "British Library in London", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (56, "None", "Cordoba, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (57, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (58, "None", "Conques, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (59, "None", "Bayeux, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (60, "None", "Chartres, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (61, "Morgan Library and Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (62, "Rheinisches Landesmuseum", "Bonn, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (63, "None", "Padua, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (64, "British Library in London", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (65, "None", "Granada, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (66, "The Cloister, New York City", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (67, "None", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (68, "National Gallery", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (69, "Bargello National Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (70, "None", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (71, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (72, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (73, "Dominican convent of Santa maria delle Grazie", "Milan, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (74, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (75, "Vatican Museums", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (76, "Vatican Museums", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (77, "Unterlinden Museum ", "Colmar, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (78, "Santa Felicita", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (79, "Schlossmuseum", "Gotha, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (80, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (81, "Bodleian Libraries, University of Oxford", "Oxford, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (82, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (83, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (84, "None", "Edirne, Turkey")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (85, "San Luigi dei Francesi, Rome", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (86, "Louvre Museum", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (87, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (88, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (89, "Santa Maria della Vittoria", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (90, "Museo Nacional de Arte", "La Paz, Bolivia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (91, "Museo Nacional de Prado", "Madrid, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (92, "National Gallery", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (93, "None", "Versailles, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (94, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (95, "Bascillica at Tepeyac", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (96, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (97, "Breamore House", "Hampshire, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (98, "National Portrait Gallery", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (99, "Philadelphia Museum of Art", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (100, "Derby Museum and Art Gallery", "Derby, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (101, "Wallace Collection", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (102, "None", "Charlottesville, Virginia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (103, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (104, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (105, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (106, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (107, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (108, "State capitol building", "Richmond, Virginia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (109, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (110, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (111, "Museum of Fine Arts", "Boston, Massachusetts")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (112, "None", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (113, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (114, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (115, "Musee D'Orsay", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (116, "Musee D'Orsay", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (117, "Library of Congress", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (118, "Mueseo National de Arte", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (119, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (120, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (121, "National Gallery", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (122, "National Gallery of Norway", "Oslo, Norway")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (123, "Museum of Fine Arts", "Boston, Massachusetts")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (124, "None", "Chicago, Illinois")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (125, "Philadelphia Museum of Art", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (126, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (127, "Los Angeles County Museum of Art", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (128, "Osterreichische Galerie Belvedere", "Versailles, Austria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (129, "Philadelphia Museum of Art", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (130, "Kunstmuseum Basel ", "Basel, Switzerland")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (131, "Pushkin Museum of Art", "Moscow, Russia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (132, "Guggenheim Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (133, "Allen Memorial Art Museum, Oberlin College", "Oberlin, Ohio")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (134, "Art Institute of Chicago", "Chicago, Illinois")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (135, "None", "Poissy, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (136, "Kunsthaus", "Zurich, Switzerland")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (137, "State Museum of Contemporary Russian History", "Moscow, Russia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (138, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (139, "MET", "Mill Run, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (140, "Museo de Arte Moderno", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (141, "Phillips Collection", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (142, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (143, "Museo Mural Diego Rivera", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (144, "San Francisco Museum of Modern Art", "San Francisco, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (145, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (146, "New York City", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (147, "Tate Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (148, "The Board", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (149, "Detroit Institute of Arts", "Detroit, Michigan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (150, "Yale University", "New Haven, Connecticut")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (151, "None", "Great Salt Lake, Utah")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (152, "None", "Castle County, Delaware")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (153, "None", "Peru")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (154, "None", "Colorado")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (155, "None", "Chiapas, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (156, "None", "Adams County, Ohio")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (157, "None", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (158, "Weltmuseum Wien", "Vienna, Austria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (159, "None", "Cusco, Peru")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (160, "Denver Art Museum", "Denver, Colorado")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (161, "None", "Peru")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (162, "Dumbarton Oaks", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (163, "National Museum of the American Indian", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (164, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (165, "Indian Arts Research Center, School for Advanced Research", "Santa Fe, New Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (166, "National Museum of Women in the Arts", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (167, "None", "Zimbabwe")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (168, "None", "Djenne, Mali")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (169, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (170, "None", "Ghana")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (171, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (172, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (173, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (174, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (175, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (176, "University of Pennsylvania Museum of Archaeology", "Philidelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (177, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (178, "Seattle Art Museum", "Seattle, Washington")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (179, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (180, "Chicago Art Institute", "Chicago, Illinois")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (181, "None", "Petra, Jordan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (182, "None", "Destroyed")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (183, "None", "Mecca, Saudi Arabia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (184, "Jokhang Temple", "Lhasa, Tibet")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (185, "None", "Jerusalem, Israel")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (186, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (187, "Morgan Library and Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (188, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (189, "Harvard Art Museums/ Arthur M. Sackler Museum", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (190, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (191, "Victoria and Albert Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (192, "None", "Sanchi, India")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (193, "None", "China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (194, "Hunan Provincial Museum", "China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (195, "None", "China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (196, "Gyeongju National Museum", "Korea")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (197, "None", "Nara, Japan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (198, "None", "Indonesia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (199, "None", "Cambodia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (200, "None", "India")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (201, "National Palace Museum", "Beijing, China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (202, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (203, "Museum of Fine Arts", "Boston, Massachusetts")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (204, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (205, "South Korea", "S. Korea")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (206, "None", "Beijing, China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (207, "None", "Kyoto, Japan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (208, "Freer Gallery of Art", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (209, "None", "Dharmapuri, India")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (210, "MOA Museum of Art", "Atami, Japan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (211, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (212, "My classroom!", "Spokane, Washington")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (213, "Nanwei", "Pohnpei Island, Federated States of Micronesia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (214, "Easter Island known as Rapa Nui", "Rapa Nui, Pacific")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (215, "Natural History Museum", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (216, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (217, "Muse du Quai Branly-Jacques Chirac", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (218, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (219, "Aukland War Memorial Museum", "Aukland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (220, "Aukland Art Gallery", "Aukland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (221, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (222, "The Penn Museum", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (223, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (224, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (225, "Washington Mall", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (226, "The Board", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (227, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (228, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (229, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (230, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (231, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (232, "Gund Gallery, Kenyon College", "Gambier, Ohio")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (233, "Chrysler Museum of Art", "Norfolk, Virginia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (234, "National Museum", "Canberra, Australia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (235, "Barbara Gladstone Gallery", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (236, "None", "Puerto Rico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (237, "Museum of New Zealand", "Aukland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (238, "Smithsonian American Art Museum", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (239, "Guggenheim Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (240, "None", "Bilbao, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (241, "Los Angeles County Museum of Art", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (242, "Centre Pompidou", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (243, "Musée d’Art Moderne Grand-Duc Jean", "Luxembourg City, Luxembourg")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (244, "Tate Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (245, "MET One in sculpture, one in African Art", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (246, "Carnegie Museum of Art", "Pittsburgh, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (247, "Brooklyn Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (248, "Tate Museum", "London")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (249, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (250, "None", "None")`);
    });
}

module.exports = {initializeDisplayed};