function initializeDisplayed(db) {

    db.serialize(() => {
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (1, "State museum of Namibia", "Keetmanshoop, Namibia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (2, "Caves of Lascaux", "Montignac, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (3, "National Museum of Anthropology", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (4, "Algerian section of the Sahara Desert", "Algeria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (5, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (6, "National Museum", "Riyad, Saudi Arabia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (7, "MET ", "New York City, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (8, "None", "England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (9, "National Gallery of Australia", "Canberra, Australia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (10, "Princeton Universtiy of Art Museum", "Princeton, New Jersey")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (11, "Dept. of Anthropology Univ. of Auckland", "Auckland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (12, "Iraq", "Warka, Iraq")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (13, "Egptian Museum", "Cairo, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (14, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (15, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (16, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (17, "None", "Cairo, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (18, "Museum of Fine Arts", "Boston, Massachusettes")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (19, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (20, "None", "Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (21, "None", "Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (22, "Neues Museum, Staatliche Museen zu Berlin", "Berlin, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (23, "the Egyptian Museum", "Cairo, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (24, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (25, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (26, "None", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (27, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (28, "Acropolis Museum", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (29, "National Etruscan Museum of Villa Giulia", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (30, "Iran", "Shiraz, Iran")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (31, "National Etruscan Museum", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (32, "Tarquinia national museum", "Tarquinia, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (33, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (34, "Museo Archeologico Nazionale di Napoli", "Naples, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (35, "None", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (36, "National Archaeological Museum", "Athens, Greece")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (37, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (38, "Pergamon Museum", "Berlin, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (39, "None", "Pompeii, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (40, "Museo Archeologico Nazionale di Napoli", "Naples, NItaly")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (41, "Palazzo Massimo alle Terme", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (42, "Palazzo Torionia", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (43, "Braccio Nuovo Vatican Museums", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (44, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (45, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (46, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (47, "Palazzo Altemps in National Museum ", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (48, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (49, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (50, "Osterreichische Nationalbibliothek", "Vienna, Austria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (51, "None", "Ravenna, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (52, "None", "Istanbul, Turkey")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (53, "Chateau de Saint-Germain-en-Laye", "Saint-Germain-en-Laye, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (54, "St. Catherine's Monastery", "Sinai, Egypt")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (55, "British Library in London", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (56, "None", "Cordoba, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (57, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (58, "None", "Conques, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (59, "None", "Bayeux, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (60, "None", "Chartres, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (61, "Morgan Library and Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (62, "Rheinisches Landesmuseum", "Bonn, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (63, "None", "Padua, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (64, "British Library in London", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (65, "None", "Granada, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (66, "The Cloister, New York City", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (67, "None", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (68, "National Gallery", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (69, "Bargello National Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (70, "None", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (71, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (72, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (73, "Dominican convent of Santa maria delle Grazie", "Milan, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (74, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (75, "Vatican Museums", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (76, "Vatican Museums", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (77, "Unterlinden Museum ", "Colmar, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (78, "Santa Felicita", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (79, "Schlossmuseum", "Gotha, Germany")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (80, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (81, "Bodleian Libraries, University of Oxford", "Oxford, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (82, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (83, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (84, "None", "Edirne, Turkey")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (85, "San Luigi dei Francesi, Rome", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (86, "Louvre Museum", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (87, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (88, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (89, "Santa Maria della Vittoria", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (90, "Museo Nacional de Arte", "La Paz, Bolivia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (91, "Museo Nacional de Prado", "Madrid, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (92, "National Gallery", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (93, "None", "Versailles, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (94, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (95, "Bascillica at Tepeyac", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (96, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (97, "Breamore House", "Hampshire, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (98, "National Portrait Gallery", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (99, "Philadelphia Museum of Art", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (100, "Derby Museum and Art Gallery", "Derby, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (101, "Wallace Collection", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (102, "None", "Charlottesville, Virginia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (103, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (104, "Uffizi Galleries' Museum", "Florence, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (105, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (106, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (107, "Louvre", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (108, "State capitol building", "Richmond, Virginia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (109, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (110, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (111, "Museum of Fine Arts", "Boston, Massachusetts")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (112, "None", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (113, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (114, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (115, "Musee D'Orsay", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (116, "Musee D'Orsay", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (117, "Library of Congress", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (118, "Mueseo National de Arte", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (119, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (120, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (121, "National Gallery", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (122, "National Gallery of Norway", "Oslo, Norway")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (123, "Museum of Fine Arts", "Boston, Massachusetts")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (124, "None", "Chicago, Illinois")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (125, "Philadelphia Museum of Art", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (126, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (127, "Los Angeles County Museum of Art", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (128, "Osterreichische Galerie Belvedere", "Versailles, Austria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (129, "Philadelphia Museum of Art", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (130, "Kunstmuseum Basel ", "Basel, Switzerland")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (131, "Pushkin Museum of Art", "Moscow, Russia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (132, "Guggenheim Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (133, "Allen Memorial Art Museum, Oberlin College", "Oberlin, Ohio")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (134, "Art Institute of Chicago", "Chicago, Illinois")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (135, "None", "Poissy, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (136, "Kunsthaus", "Zurich, Switzerland")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (137, "State Museum of Contemporary Russian History", "Moscow, Russia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (138, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (139, "MET", "Mill Run, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (140, "Museo de Arte Moderno", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (141, "Phillips Collection", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (142, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (143, "Museo Mural Diego Rivera", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (144, "San Francisco Museum of Modern Art", "San Francisco, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (145, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (146, "New York City", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (147, "Tate Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (148, "The Board", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (149, "Detroit Institute of Arts", "Detroit, Michigan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (150, "Yale University", "New Haven, Connecticut")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (151, "None", "Great Salt Lake, Utah")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (152, "None", "Castle County, Delaware")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (153, "None", "Peru")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (154, "None", "Colorado")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (155, "None", "Chiapas, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (156, "None", "Adams County, Ohio")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (157, "None", "Mexico City, Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (158, "Weltmuseum Wien", "Vienna, Austria")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (159, "None", "Cusco, Peru")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (160, "Denver Art Museum", "Denver, Colorado")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (161, "None", "Peru")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (162, "Dumbarton Oaks", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (163, "National Museum of the American Indian", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (164, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (165, "Indian Arts Research Center, School for Advanced Research", "Santa Fe, New Mexico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (166, "National Museum of Women in the Arts", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (167, "None", "Zimbabwe")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (168, "None", "Djenne, Mali")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (169, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (170, "None", "Ghana")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (171, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (172, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (173, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (174, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (175, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (176, "University of Pennsylvania Museum of Archaeology", "Philidelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (177, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (178, "Seattle Art Museum", "Seattle, Washington")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (179, "Brooklyn Museum, NYC", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (180, "Chicago Art Institute", "Chicago, Illinois")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (181, "None", "Petra, Jordan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (182, "None", "Destroyed")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (183, "None", "Mecca, Saudi Arabia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (184, "Jokhang Temple", "Lhasa, Tibet")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (185, "None", "Jerusalem, Israel")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (186, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (187, "Morgan Library and Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (188, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (189, "Harvard Art Museums/ Arthur M. Sackler Museum", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (190, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (191, "Victoria and Albert Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (192, "None", "Sanchi, India")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (193, "None", "China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (194, "Hunan Provincial Museum", "China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (195, "None", "China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (196, "Gyeongju National Museum", "Korea")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (197, "None", "Nara, Japan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (198, "None", "Indonesia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (199, "None", "Cambodia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (200, "None", "India")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (201, "National Palace Museum", "Beijing, China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (202, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (203, "Museum of Fine Arts", "Boston, Massachusetts")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (204, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (205, "South Korea", "S. Korea")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (206, "None", "Beijing, China")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (207, "None", "Kyoto, Japan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (208, "Freer Gallery of Art", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (209, "None", "Dharmapuri, India")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (210, "MOA Museum of Art", "Atami, Japan")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (211, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (212, "My classroom!", "Spokane, Washington")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (213, "Nanwei", "Pohnpei Island, Federated States of Micronesia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (214, "Easter Island known as Rapa Nui", "Rapa Nui, Pacific")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (215, "Natural History Museum", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (216, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (217, "Muse du Quai Branly-Jacques Chirac", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (218, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (219, "Aukland War Memorial Museum", "Aukland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (220, "Aukland Art Gallery", "Aukland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (221, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (222, "The Penn Museum", "Philadelphia, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (223, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (224, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (225, "Washington Mall", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (226, "The Board", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (227, "British Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (228, "MET", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (229, "None", "None")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (230, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (231, "MOMA", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (232, "Gund Gallery, Kenyon College", "Gambier, Ohio")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (233, "Chrysler Museum of Art", "Norfolk, Virginia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (234, "National Museum", "Canberra, Australia")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (235, "Barbara Gladstone Gallery", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (236, "None", "Puerto Rico")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (237, "Museum of New Zealand", "Aukland, New Zealand")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (238, "Smithsonian American Art Museum", "Washington DC")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (239, "Guggenheim Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (240, "None", "Bilbao, Spain")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (241, "Los Angeles County Museum of Art", "Los Angeles, California")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (242, "Centre Pompidou", "Paris, France")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (243, "Musée d’Art Moderne Grand-Duc Jean", "Luxembourg City, Luxembourg")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (244, "Tate Museum", "London, England")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (245, "MET One in sculpture, one in African Art", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (246, "Carnegie Museum of Art", "Pittsburgh, Pennsylvania")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (247, "Brooklyn Museum", "NYC, New York")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (248, "Tate Museum", "London")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (249, "None", "Rome, Italy")`);
        db.run(`INSERT OR IGNORE INTO Displayed (id, museum, displayedLocation) VALUES (250, "None", "None")`);

        db.run(`UPDATE Displayed SET latitude = -26.577989, longitude = 18.141563 WHERE id = 1`);
        db.run(`UPDATE Displayed SET latitude = 45.027181, longitude = 1.166900 WHERE id = 2`);
        db.run(`UPDATE Displayed SET latitude = 19.426003, longitude = -99.186279 WHERE id = 3`);
        db.run(`UPDATE Displayed SET latitude = 24.000000, longitude = 8.000000 WHERE id = 4`);
        db.run(`UPDATE Displayed SET latitude = 40.770437, longitude = -73.963244 WHERE id = 5`);
        db.run(`UPDATE Displayed SET latitude = 24.684100, longitude = 46.721850 WHERE id = 6`);
        db.run(`UPDATE Displayed SET latitude = 40.745437, longitude = -73.963244 WHERE id = 7`);
        db.run(`UPDATE Displayed SET latitude = 51.509865, longitude = -0.118092 WHERE id = 8`);
        db.run(`UPDATE Displayed SET latitude = -35.300399, longitude = 149.136781 WHERE id = 9`);
        db.run(`UPDATE Displayed SET latitude = 40.347069, longitude = -74.657646 WHERE id = 10`);
        db.run(`UPDATE Displayed SET latitude = -36.852338, longitude = 174.769107 WHERE id = 11`);
        db.run(`UPDATE Displayed SET latitude = 29.913317, longitude = 45.299386 WHERE id = 12`);
        db.run(`UPDATE Displayed SET latitude = 30.047652, longitude = 31.233615 WHERE id = 13`);
        db.run(`UPDATE Displayed SET latitude = 40.8529437, longitude = -73.963244 WHERE id = 14`);
        db.run(`UPDATE Displayed SET latitude = 48.860611, longitude = 2.337644 WHERE id = 15`);
        db.run(`UPDATE Displayed SET latitude = 51.519413, longitude = -0.126957 WHERE id = 16`);
        db.run(`UPDATE Displayed SET latitude = 29.979234, longitude = 31.134202 WHERE id = 17`);
        db.run(`UPDATE Displayed SET latitude = 42.339381, longitude = -71.094048 WHERE id = 18`);
        db.run(`UPDATE Displayed SET latitude = 49.010611, longitude = 2.337644 WHERE id = 19`);
        db.run(`UPDATE Displayed SET latitude = 30.044420, longitude = 31.235712 WHERE id = 20`);
        db.run(`UPDATE Displayed SET latitude = 30.194420, longitude = 31.235712 WHERE id = 21`);
        db.run(`UPDATE Displayed SET latitude = 52.516275, longitude = 13.377704 WHERE id = 22`);
        db.run(`UPDATE Displayed SET latitude = 30.194420, longitude = 31.235712 WHERE id = 23`);
        db.run(`UPDATE Displayed SET latitude = 41.029437, longitude = -73.963244 WHERE id = 24`);
        db.run(`UPDATE Displayed SET latitude = 40.999, longitude = -73.963244 WHERE id = 25`);
        db.run(`UPDATE Displayed SET latitude = 37.983810, longitude = 23.727539 WHERE id = 26`);
        db.run(`UPDATE Displayed SET latitude = 38.133810, longitude = 23.727539 WHERE id = 27`);
        db.run(`UPDATE Displayed SET latitude = 37.971532, longitude = 23.726591 WHERE id = 28`);
        db.run(`UPDATE Displayed SET latitude = 41.910241, longitude = 12.453056 WHERE id = 29`);
        db.run(`UPDATE Displayed SET latitude = 29.615074, longitude = 52.531098 WHERE id = 30`);
        db.run(`UPDATE Displayed SET latitude = 42.060241, longitude = 12.453056 WHERE id = 31`);
        db.run(`UPDATE Displayed SET latitude = 42.262537, longitude = 11.821849 WHERE id = 32`);
        db.run(`UPDATE Displayed SET latitude = 49.010611, longitude = 2.337644 WHERE id = 33`);
        db.run(`UPDATE Displayed SET latitude = 40.853290, longitude = 14.305573 WHERE id = 34`);
        db.run(`UPDATE Displayed SET latitude = 38.133810, longitude = 23.727539 WHERE id = 35`);
        db.run(`UPDATE Displayed SET latitude = 38.133810, longitude = 23.727539 WHERE id = 36`);
        db.run(`UPDATE Displayed SET latitude = 48.856613, longitude = 2.352222 WHERE id = 37`);
        db.run(`UPDATE Displayed SET latitude = 52.520008, longitude = 13.404954 WHERE id = 38`);
        db.run(`UPDATE Displayed SET latitude = 40.752726, longitude = 14.488670 WHERE id = 39`);
        db.run(`UPDATE Displayed SET latitude = 41.003290, longitude = 14.305573 WHERE id = 40`);
        db.run(`UPDATE Displayed SET latitude = 41.893056, longitude = 12.482778 WHERE id = 41`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 42`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 43`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 44`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 45`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 46`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 47`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 48`);
        db.run(`UPDATE Displayed SET latitude = 42.043056, longitude = 12.482778 WHERE id = 49`);
        db.run(`UPDATE Displayed SET latitude = 48.208174, longitude = 16.373819 WHERE id = 50`);
        db.run(`UPDATE Displayed SET latitude = 45.042865, longitude = 7.576662 WHERE id = 51`);
        db.run(`UPDATE Displayed SET latitude = 41.008238, longitude = 28.978359 WHERE id = 52`);
        db.run(`UPDATE Displayed SET latitude = 48.895385, longitude = 2.090635 WHERE id = 53`);
        db.run(`UPDATE Displayed SET latitude = 28.539978, longitude = 33.977815 WHERE id = 54`);
        db.run(`UPDATE Displayed SET latitude = 51.527065, longitude = -0.108382 WHERE id = 55`);
        db.run(`UPDATE Displayed SET latitude = 37.893055, longitude = -4.779167 WHERE id = 56`);
        db.run(`UPDATE Displayed SET latitude = 40.809437, longitude = -73.963244 WHERE id = 57`);
        db.run(`UPDATE Displayed SET latitude = 44.591852, longitude = 2.166457 WHERE id = 58`);
        db.run(`UPDATE Displayed SET latitude = 49.275278, longitude = -0.701944 WHERE id = 59`);
        db.run(`UPDATE Displayed SET latitude = 47.377778, longitude = 1.674722 WHERE id = 60`);
        db.run(`UPDATE Displayed SET latitude = 40.753303, longitude = -73.982787 WHERE id = 61`);
        db.run(`UPDATE Displayed SET latitude = 50.736062, longitude = 7.095151 WHERE id = 62`);
        db.run(`UPDATE Displayed SET latitude = 45.406437, longitude = 11.876292 WHERE id = 63`);
        db.run(`UPDATE Displayed SET latitude = 51.677065, longitude = -0.108382 WHERE id = 64`);
        db.run(`UPDATE Displayed SET latitude = 37.183333, longitude = -3.590556 WHERE id = 65`);
        db.run(`UPDATE Displayed SET latitude = 40.629437, longitude = -73.963244 WHERE id = 66`);
        db.run(`UPDATE Displayed SET latitude = 43.769056, longitude = 11.255814 WHERE id = 67`);
        db.run(`UPDATE Displayed SET latitude = 51.510159, longitude = -0.127647 WHERE id = 68`);
        db.run(`UPDATE Displayed SET latitude = 43.774941, longitude = 11.261829 WHERE id = 69`);
        db.run(`UPDATE Displayed SET latitude = 43.924941, longitude = 11.261829 WHERE id = 70`);
        db.run(`UPDATE Displayed SET latitude = 43.862587, longitude = 11.370026 WHERE id = 71`);
        db.run(`UPDATE Displayed SET latitude = 43.877587, longitude = 11.270026 WHERE id = 72`);
        db.run(`UPDATE Displayed SET latitude = 45.466944, longitude = 9.190556 WHERE id = 73`);
        db.run(`UPDATE Displayed SET latitude = 40.699437, longitude = -73.963244 WHERE id = 74`);
        db.run(`UPDATE Displayed SET latitude = 41.903079, longitude = 12.453322 WHERE id = 75`);
        db.run(`UPDATE Displayed SET latitude = 42.053079, longitude = 12.453322 WHERE id = 76`);
        db.run(`UPDATE Displayed SET latitude = 48.080645, longitude = 7.358596 WHERE id = 77`);
        db.run(`UPDATE Displayed SET latitude = 43.764084, longitude = 11.255767 WHERE id = 78`);
        db.run(`UPDATE Displayed SET latitude = 50.975375, longitude = 10.708762 WHERE id = 79`);
        db.run(`UPDATE Displayed SET latitude = 43.942587, longitude = 11.270026 WHERE id = 80`);
        db.run(`UPDATE Displayed SET latitude = 51.754816, longitude = -1.254366 WHERE id = 81`);
        db.run(`UPDATE Displayed SET latitude = 42.053079, longitude = 12.453322 WHERE id = 82`);
        db.run(`UPDATE Displayed SET latitude = 40.799437, longitude = -73.963244 WHERE id = 83`);
        db.run(`UPDATE Displayed SET latitude = 41.671964, longitude = 26.551686 WHERE id = 84`);
        db.run(`UPDATE Displayed SET latitude = 41.787729, longitude = 12.586114 WHERE id = 85`);
        db.run(`UPDATE Displayed SET latitude = 48.712134, longitude = 2.318058 WHERE id = 86`);
        db.run(`UPDATE Displayed SET latitude = 40.7329437, longitude = -73.963244 WHERE id = 87`);
        db.run(`UPDATE Displayed SET latitude = 42.053079, longitude = 12.453322 WHERE id = 88`);
        db.run(`UPDATE Displayed SET latitude = 41.905278, longitude = 12.454722 WHERE id = 89`);
        db.run(`UPDATE Displayed SET latitude = -16.500000, longitude = -68.119167 WHERE id = 90`);
        db.run(`UPDATE Displayed SET latitude = 40.413778, longitude = -3.692222 WHERE id = 91`);
        db.run(`UPDATE Displayed SET latitude = 38.889312, longitude = -77.050216 WHERE id = 92`);
        db.run(`UPDATE Displayed SET latitude = 48.805028, longitude = 2.120055 WHERE id = 93`);
        db.run(`UPDATE Displayed SET latitude = 40.678207, longitude = -73.975985 WHERE id = 94`);
        db.run(`UPDATE Displayed SET latitude = 19.496913, longitude = -99.055537 WHERE id = 95`);
        db.run(`UPDATE Displayed SET latitude = 43.802587, longitude = 11.470026 WHERE id = 96`);
        db.run(`UPDATE Displayed SET latitude = 51.052230, longitude = -1.152420 WHERE id = 97`);
        db.run(`UPDATE Displayed SET latitude = 51.507871, longitude = -0.128108 WHERE id = 98`);
        db.run(`UPDATE Displayed SET latitude = 39.958895, longitude = -75.181162 WHERE id = 99`);
        db.run(`UPDATE Displayed SET latitude = 52.918400, longitude = -1.490100 WHERE id = 100`);
        db.run(`UPDATE Displayed SET latitude = 51.527800, longitude = -0.142200 WHERE id = 101`);
        db.run(`UPDATE Displayed SET latitude = 38.029300, longitude = -78.479200 WHERE id = 102`);
        db.run(`UPDATE Displayed SET latitude = 48.886980, longitude = 2.473121 WHERE id = 103`);
        db.run(`UPDATE Displayed SET latitude = 43.815425, longitude = 11.114363 WHERE id = 104`);
        db.run(`UPDATE Displayed SET latitude = 40.875940, longitude = -74.078004 WHERE id = 105`);
        db.run(`UPDATE Displayed SET latitude = 48.906980, longitude = 2.493121 WHERE id = 106`);
        db.run(`UPDATE Displayed SET latitude = 48.886980, longitude = 2.493121 WHERE id = 107`);
        db.run(`UPDATE Displayed SET latitude = 37.540700, longitude = -77.436000 WHERE id = 108`);
        db.run(`UPDATE Displayed SET latitude = 40.875940, longitude = -74.238004 WHERE id = 109`);
        db.run(`UPDATE Displayed SET latitude = 42.360100, longitude = -71.058900 WHERE id = 111`);
        db.run(`UPDATE Displayed SET latitude = 51.632941, longitude = -0.209895 WHERE id = 112`);
        db.run(`UPDATE Displayed SET latitude = 40.672200, longitude = -73.963400 WHERE id = 114`);
        db.run(`UPDATE Displayed SET latitude = 48.860000, longitude = 2.326600 WHERE id = 115`);
        db.run(`UPDATE Displayed SET latitude = 49.010000, longitude = 2.326600 WHERE id = 116`);
        db.run(`UPDATE Displayed SET latitude = 38.889500, longitude = -77.035300 WHERE id = 117`);
        db.run(`UPDATE Displayed SET latitude = 19.432600, longitude = -99.133200 WHERE id = 118`);
        db.run(`UPDATE Displayed SET latitude = 40.822200, longitude = -73.963400 WHERE id = 119`);
        db.run(`UPDATE Displayed SET latitude = 40.761400, longitude = -73.977600 WHERE id = 120`);
        db.run(`UPDATE Displayed SET latitude = 40.875940, longitude = -73.858004 WHERE id = 121`);
        db.run(`UPDATE Displayed SET latitude = 59.913900, longitude = 10.752200 WHERE id = 122`);
        db.run(`UPDATE Displayed SET latitude = 42.510100, longitude = -71.058900 WHERE id = 123`);
        db.run(`UPDATE Displayed SET latitude = 41.878100, longitude = -87.629800 WHERE id = 124`);
        db.run(`UPDATE Displayed SET latitude = 39.964000, longitude = -75.179000 WHERE id = 125`);
        db.run(`UPDATE Displayed SET latitude = 41.011400, longitude = -73.977600 WHERE id = 126`);
        db.run(`UPDATE Displayed SET latitude = 34.052200, longitude = -118.243700 WHERE id = 127`);
        db.run(`UPDATE Displayed SET latitude = 48.200000, longitude = 16.373800 WHERE id = 128`);
        db.run(`UPDATE Displayed SET latitude = 40.114000, longitude = -75.179000 WHERE id = 129`);
        db.run(`UPDATE Displayed SET latitude = 47.559600, longitude = 7.588600 WHERE id = 130`);
        db.run(`UPDATE Displayed SET latitude = 55.751200, longitude = 37.618400 WHERE id = 131`);
        db.run(`UPDATE Displayed SET latitude = 40.773500, longitude = -73.965400 WHERE id = 132`);
        db.run(`UPDATE Displayed SET latitude = 41.291700, longitude = -81.341300 WHERE id = 133`);
        db.run(`UPDATE Displayed SET latitude = 41.879600, longitude = -87.624400 WHERE id = 134`);
        db.run(`UPDATE Displayed SET latitude = 49.089400, longitude = 2.035200 WHERE id = 135`);
        db.run(`UPDATE Displayed SET latitude = 47.373100, longitude = 8.540000 WHERE id = 136`);
        db.run(`UPDATE Displayed SET latitude = 55.663774, longitude = 37.738610 WHERE id = 137`);
        db.run(`UPDATE Displayed SET latitude = 40.711400, longitude = -73.977600 WHERE id = 138`);
        db.run(`UPDATE Displayed SET latitude = 40.767000, longitude = -79.538000 WHERE id = 139`);
        db.run(`UPDATE Displayed SET latitude = 19.582600, longitude = -99.133200 WHERE id = 140`);
        db.run(`UPDATE Displayed SET latitude = 38.900400, longitude = -77.036900 WHERE id = 141`);
        db.run(`UPDATE Displayed SET latitude = 40.911400, longitude = -73.977600 WHERE id = 142`);
        db.run(`UPDATE Displayed SET latitude = 19.582600, longitude = -99.133200 WHERE id = 143`);
        db.run(`UPDATE Displayed SET latitude = 37.791200, longitude = -122.403600 WHERE id = 144`);
        db.run(`UPDATE Displayed SET latitude = 40.712800, longitude = -74.006000 WHERE id = 146`);
        db.run(`UPDATE Displayed SET latitude = 51.372690, longitude = -0.069946 WHERE id = 147`);
        db.run(`UPDATE Displayed SET latitude = 34.202200, longitude = -118.243700 WHERE id = 148`);
        db.run(`UPDATE Displayed SET latitude = 42.331400, longitude = -83.045800 WHERE id = 149`);
        db.run(`UPDATE Displayed SET latitude = 41.316300, longitude = -72.922300 WHERE id = 150`);
        db.run(`UPDATE Displayed SET latitude = 40.760801, longitude = -112.287701 WHERE id = 151`);
        db.run(`UPDATE Displayed SET latitude = 39.566401, longitude = -75.608101 WHERE id = 152`);
        db.run(`UPDATE Displayed SET latitude = -9.595471, longitude = -77.175835 WHERE id = 153`);
        db.run(`UPDATE Displayed SET latitude = 37.230871, longitude = -108.461832 WHERE id = 154`);
        db.run(`UPDATE Displayed SET latitude = 16.898919, longitude = -90.965937 WHERE id = 155`);
        db.run(`UPDATE Displayed SET latitude = 39.023679, longitude = -83.431301 WHERE id = 156`);
        db.run(`UPDATE Displayed SET latitude = 19.436249, longitude = -99.129572 WHERE id = 157`);
        db.run(`UPDATE Displayed SET latitude = 48.206388, longitude = 16.372504 WHERE id = 158`);
        db.run(`UPDATE Displayed SET latitude = -13.531949, longitude = -71.967461 WHERE id = 159`);
        db.run(`UPDATE Displayed SET latitude = 52.456739, longitude = 13.292143 WHERE id = 160`);
        db.run(`UPDATE Displayed SET latitude = -13.163139, longitude = -72.544961 WHERE id = 161`);
        db.run(`UPDATE Displayed SET latitude = 38.914200, longitude = -77.064044 WHERE id = 162`);
        db.run(`UPDATE Displayed SET latitude = 40.829438, longitude = -73.813243 WHERE id = 163`);
        db.run(`UPDATE Displayed SET latitude = 40.781326, longitude = -73.973987 WHERE id = 164`);
        db.run(`UPDATE Displayed SET latitude = 35.675343, longitude = -105.931325 WHERE id = 165`);
        db.run(`UPDATE Displayed SET latitude = 38.900088, longitude = -77.029135 WHERE id = 166`);
        db.run(`UPDATE Displayed SET latitude = -19.015402, longitude = 29.154898 WHERE id = 167`);
        db.run(`UPDATE Displayed SET latitude = 13.905171, longitude = -4.555414 WHERE id = 168`);
        db.run(`UPDATE Displayed SET latitude = 40.629439, longitude = -73.813242 WHERE id = 169`);
        db.run(`UPDATE Displayed SET latitude = 6.747045, longitude = -1.520860 WHERE id = 170`);
        db.run(`UPDATE Displayed SET latitude = 40.821207, longitude = -73.813630 WHERE id = 171`);
        db.run(`UPDATE Displayed SET latitude = 40.735504, longitude = -73.919307 WHERE id = 172`);
        db.run(`UPDATE Displayed SET latitude = 40.696520, longitude = -73.947404 WHERE id = 173`);
        db.run(`UPDATE Displayed SET latitude = 40.629438, longitude = -74.263239 WHERE id = 174`);
        db.run(`UPDATE Displayed SET latitude = 40.789437, longitude = -74.063244 WHERE id = 175`);
        db.run(`UPDATE Displayed SET latitude = 39.949243, longitude = -75.191003 WHERE id = 176`);
        db.run(`UPDATE Displayed SET latitude = 40.629439, longitude = -73.963238 WHERE id = 177`);
        db.run(`UPDATE Displayed SET latitude = 47.607100, longitude = -122.338100 WHERE id = 178`);
        db.run(`UPDATE Displayed SET latitude = 41.134779, longitude = -73.761196 WHERE id = 179`);
        db.run(`UPDATE Displayed SET latitude = 41.882638, longitude = -87.773681 WHERE id = 180`);
        db.run(`UPDATE Displayed SET latitude = 30.329003, longitude = 35.444663 WHERE id = 181`);
        db.run(`UPDATE Displayed SET latitude = 34.832065, longitude = 67.826755 WHERE id = 182`);
        db.run(`UPDATE Displayed SET latitude = 21.422471, longitude = 39.826205 WHERE id = 183`);
        db.run(`UPDATE Displayed SET latitude = 29.661944, longitude = 91.140278 WHERE id = 184`);
        db.run(`UPDATE Displayed SET latitude = 31.778021, longitude = 35.235405 WHERE id = 185`);
        db.run(`UPDATE Displayed SET latitude = 32.669701, longitude = 51.685257 WHERE id = 186`);
        db.run(`UPDATE Displayed SET latitude = 40.629440, longitude = -74.113236 WHERE id = 187`);
        db.run(`UPDATE Displayed SET latitude = 48.793530, longitude = 2.471806 WHERE id = 188`);
        db.run(`UPDATE Displayed SET latitude = 42.273100, longitude = -71.901999 WHERE id = 189`);
        db.run(`UPDATE Displayed SET latitude = 40.879437, longitude = -73.963244 WHERE id = 190`);
        db.run(`UPDATE Displayed SET latitude = 51.346641, longitude = -0.322178 WHERE id = 191`);
        db.run(`UPDATE Displayed SET latitude = 23.479392, longitude = 77.739587 WHERE id = 192`);
        db.run(`UPDATE Displayed SET latitude = 34.367277, longitude = 109.214236 WHERE id = 193`);
        db.run(`UPDATE Displayed SET latitude = 28.211912, longitude = 112.992145 WHERE id = 194`);
        db.run(`UPDATE Displayed SET latitude = 34.559501, longitude = 112.467875 WHERE id = 195`);
        db.run(`UPDATE Displayed SET latitude = 35.829398, longitude = 129.227904 WHERE id = 196`);
        db.run(`UPDATE Displayed SET latitude = 34.688987, longitude = 135.839813 WHERE id = 197`);
        db.run(`UPDATE Displayed SET latitude = -7.607874, longitude = 110.203749 WHERE id = 198`);
        db.run(`UPDATE Displayed SET latitude = 13.412471, longitude = 103.866982 WHERE id = 199`);
        db.run(`UPDATE Displayed SET latitude = 24.852173, longitude = 79.921702 WHERE id = 200`);
        db.run(`UPDATE Displayed SET latitude = 39.926345, longitude = 116.407155 WHERE id = 201`);
        db.run(`UPDATE Displayed SET latitude = 41.029437, longitude = -73.563244 WHERE id = 202`);
        db.run(`UPDATE Displayed SET latitude = 42.489100, longitude = -70.944200 WHERE id = 203`);
        db.run(`UPDATE Displayed SET latitude = 51.669413, longitude = -0.126957 WHERE id = 204`);
        db.run(`UPDATE Displayed SET latitude = 36.557306, longitude = 127.532134 WHERE id = 205`);
        db.run(`UPDATE Displayed SET latitude = 39.916345, longitude = 116.397155 WHERE id = 206`);
        db.run(`UPDATE Displayed SET latitude = 35.034494, longitude = 135.718263 WHERE id = 207`);
        db.run(`UPDATE Displayed SET latitude = 38.888119, longitude = -77.027328 WHERE id = 208`);
        db.run(`UPDATE Displayed SET latitude = 27.175009, longitude = 78.042091 WHERE id = 209`);
        db.run(`UPDATE Displayed SET latitude = 35.108578, longitude = 139.077190 WHERE id = 210`);
        db.run(`UPDATE Displayed SET latitude = 47.658074, longitude = -117.408239 WHERE id = 212`);
        db.run(`UPDATE Displayed SET latitude = 6.840412, longitude = 158.331692 WHERE id = 213`);
        db.run(`UPDATE Displayed SET latitude = -27.112990, longitude = -109.349581 WHERE id = 214`);
        db.run(`UPDATE Displayed SET latitude = 51.480875, longitude = -0.005289 WHERE id = 215`);
        db.run(`UPDATE Displayed SET latitude = 46.202055, longitude = 6.146561 WHERE id = 217`);
        db.run(`UPDATE Displayed SET latitude = -36.851354, longitude = 174.766237 WHERE id = 219`);
        db.run(`UPDATE Displayed SET latitude = -36.861354, longitude = 174.776237 WHERE id = 220`);
        db.run(`UPDATE Displayed SET latitude = 40.779437, longitude = -73.963244 WHERE id = 221`);
        db.run(`UPDATE Displayed SET latitude = 40.874956, longitude = -74.083758 WHERE id = 224`);
        db.run(`UPDATE Displayed SET latitude = 38.891248, longitude = -77.047696 WHERE id = 225`);
        db.run(`UPDATE Displayed SET latitude = 34.054386, longitude = -118.250649 WHERE id = 226`);
        db.run(`UPDATE Displayed SET latitude = 40.636625, longitude = -73.894417 WHERE id = 230`);
        db.run(`UPDATE Displayed SET latitude = 40.375100, longitude = -82.396900 WHERE id = 232`);
        db.run(`UPDATE Displayed SET latitude = 36.856399, longitude = -76.292988 WHERE id = 233`);
        db.run(`UPDATE Displayed SET latitude = -19.491411, longitude = 132.550960 WHERE id = 234`);
        db.run(`UPDATE Displayed SET latitude = 18.448275, longitude = -66.066284 WHERE id = 236`);
        db.run(`UPDATE Displayed SET latitude = -41.290456, longitude = 174.782089 WHERE id = 237`);
        db.run(`UPDATE Displayed SET latitude = 38.897990, longitude = -77.023006 WHERE id = 238`);
        db.run(`UPDATE Displayed SET latitude = 40.782980, longitude = -73.958971 WHERE id = 239`);
        db.run(`UPDATE Displayed SET latitude = 43.268671, longitude = -2.934012 WHERE id = 240`);
        db.run(`UPDATE Displayed SET latitude = 34.078036, longitude = -118.474095 WHERE id = 241`);
        db.run(`UPDATE Displayed SET latitude = 48.860642, longitude = 2.352245 WHERE id = 242`);
        db.run(`UPDATE Displayed SET latitude = 49.617095, longitude = 6.140337 WHERE id = 243`);
        db.run(`UPDATE Displayed SET latitude = 40.761433, longitude = -74.077622 WHERE id = 245`);
        db.run(`UPDATE Displayed SET latitude = 40.443263, longitude = -79.950029 WHERE id = 246`);
        db.run(`UPDATE Displayed SET latitude = 40.817312, longitude = -73.929677 WHERE id = 247`);
        db.run(`UPDATE Displayed SET latitude = 41.928287, longitude = 12.467025 WHERE id = 249`);
    });
}

module.exports = {initializeDisplayed};