
function initializeImages(db) {
    db.serialize(() => {
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (1, "1_Apollo 11 stones.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (2, "2_Great Hall of the Bulls.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (3, "3_Camelid sacrum in the shape of a canine.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (4, "4_Running horned woman.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (5, "5_Beaker with ibex motifs.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (6, "6_Anthropomorphic stele.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (7, "7_Jade cong.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (8, "8_Stonehenge.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (8, "9_Stonehenge.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (9, "10_The Ambum Stone.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (10, "11_Tlaticlo female figure.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (11, "12_Terra cotta fragment.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (12, "13_White Temple and its ziggurat.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (12, "14_White Temple and its ziggurat.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (13, "15_Palette of King Narmer.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (13, "16_Palette of King Narmer.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (14, "17_Statues of votive figures, from the Square Temple at Eshnunna.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (15, "18_Seated scribe.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (16, "19_Standard of Ur from the Royal Tombs at Ur.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (16, "20_Standard of Ur from the Royal Tombs at Ur.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (17, "21_Great Pyramids (Menkaura, Khafre, Khufu).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (17, "22_Great Pyramids (Menkaura, Khafre, Khufu).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (18, "23_King Menkaura and queen.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (19, "24_The Code of Hammurabi.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (20, "25_Temple of Amun-Re and Hypostyle Hall.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (20, "26_Temple of Amun-Re and Hypostyle Hall.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (20, "27_Temple of Amun-Re and Hypostyle Hall.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (21, "28_Mortuary temple of Hatshepsut.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (21, "29_Mortuary temple of Hatshepsut.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (22, "30_Akhenaten, Nefertiti, and three daughters.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (23, "31_Tutankhamun’s tomb, innermost coffin.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (24, "32_Last judgment of Hu-Nefer, from his tomb (page from the Book of the Dead).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (25, "33_Lamassu from the citadel of Sargon II, Dur Sharrukin.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (26, "34_Athenian agora.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (27, "35_Anavysos Kouros.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (27, "36_Anavysos Kouros.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (28, "37_Peplos Kore from the Acropolis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (29, "38_Sarcophagus of the Spouses.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (30, "39_Audience Halll (apadana) of Darius and Xerxes.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (30, "40_Audience Halll (apadana) of Darius and Xerxes.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (31, "41_Temple of Minerva (Veii, near Rome, Italy) and sculpture of Apollo.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (31, "42_Temple of Minerva (Veii, near Rome, Italy) and sculpture of Apollo.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (31, "43_Temple of Minerva (Veii, near Rome, Italy) and sculpture of Apollo.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (32, "44_Tomb of the Triclinium.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (33, "45_Niobides Krater.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (34, "46_Doryphoros (Spear Bearer).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (35, "47_Acropolis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (35, "48_Acropolis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (35, "49_Acropolis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (35, "50_Acropolis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (35, "51_Acropolis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (35, "52_Acropolis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (36, "53_Grave stele of Hegeso.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (37, "54_Winged Victory of Samothrace.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (38, "55_Great Altar of Zeus and Athena at Pergamon.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (38, "56_Great Altar of Zeus and Athena at Pergamon.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (38, "57_Great Altar of Zeus and Athena at Pergamon.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (39, "58_House of the Vettii.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (39, "59_House of the Vettii.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (39, "60_House of the Vettii.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (40, "61_Alexander Mosaic from the House of Faun, Pompeii.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (41, "62_Seated Boxer.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (42, "63_Head of a Roman patrician.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (42, "64_Head of a Roman patrician.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (43, "65_Augustus of Prima Porta.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (44, "66_Colosseum (Flavian Amphitheater).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (45, "67_Forum of Trajan.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (45, "68_Forum of Trajan.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (45, "69_Forum of Trajan.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (45, "70_Forum of Trajan.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (46, "71_Pantheon.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (46, "72_Pantheon.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (47, "73_Ludovisi Battle Sarcophagus.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (48, "74_Catacomb of Priscilla.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (48, "75_Catacomb of Priscilla.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (48, "76_Catacomb of Priscilla.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (49, "77_Santa Sabrina.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (49, "78_Santa Sabrina.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (49, "79_Santa Sabrina.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (50, "80_Rebecca and Eliezer at the Well and Jacob Wrestling the Angel, from the Vienna Genesis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (50, "81_Rebecca and Eliezer at the Well and Jacob Wrestling the Angel, from the Vienna Genesis.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (51, "82_San Vitale.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (51, "83_San Vitale.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (51, "84_San Vitale.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (51, "85_San Vitale.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (51, "86_San Vitale.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (52, "87_Hagia Sophia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (52, "88_Hagia Sophia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (53, "89_Merovingian looped fibulae.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (54, "90_Virgin (Theotokos) and Child between Saints Theodore and George.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (55, "91_Lindisfarne Gospels_ St. Matthew, cross-carpet page; St. Luke portrait page; St. Luke incipit page.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (55, "92_Lindisfarne Gospels_ St. Matthew, cross-carpet page; St. Luke portrait page; St. Luke incipit page.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (55, "93_Lindisfarne Gospels_ St. Matthew, cross-carpet page; St. Luke portrait page; St. Luke incipit page.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (56, "94_Great Mosque.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (56, "95_Great Mosque.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (56, "96_Great Mosque.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (56, "97_Great Mosque.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (56, "98_Great Mosque.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (57, "99_Pyxis of al-Mughira.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (58, "100_Church of Sainte-Foy.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (58, "101_Church of Sainte-Foy.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (58, "102_Church of Sainte-Foy.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (58, "103_Church of Sainte-Foy.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (59, "104_Bayeux Tapestry.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (59, "105_Bayeux Tapestry.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (60, "106_Chartres Cathedral.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (60, "107_Chartres Cathedral.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (60, "108_Chartres Cathedral.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (60, "109_Chartres Cathedral.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (60, "110_Chartres Cathedral.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (60, "111_Chartres Cathedral.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (61, "112_Dedication Page with Blanche of Castile and King Louis IX of France, Scenes from the Apocalypse from Bibles moralisées.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (61, "113_Dedication Page with Blanche of Castile and King Louis IX of France, Scenes from the Apocalypse from Bibles moralisées.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (62, "116_Röttgen Pietà.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (63, "117_Arena (Scrovegni) Chapel, including Lamentation.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (63, "118_Arena (Scrovegni) Chapel, including Lamentation.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (63, "119_Arena (Scrovegni) Chapel, including Lamentation.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (64, "122_4 Golden Haggadah (The Plagues of Egypt, Scenes of Liberation, and Preparation for Passover).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (64, "123_4 Golden Haggadah (The Plagues of Egypt, Scenes of Liberation, and Preparation for Passover).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (65, "126_Alhambra.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (65, "127_Alhambra.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (65, "128_Alhambra.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (65, "129_Alhambra.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (66, "130_Annunciation Triptych (Merode Altarpiece).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (67, "131_Pazzi Chapel, Basilica di Santa Croce.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (67, "132_Pazzi Chapel, Basilica di Santa Croce.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (68, "133_The Arnolfini Portrait.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (69, "134_David.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (70, "135_Palazzo Rucellai.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (71, "136_Madonna and Child with Two Angels.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (72, "137_Birth of Venus.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (73, "138_Last Supper.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (74, "139_Adam and Eve.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (75, "140_Sistine Chapel ceiling and altar wall frescoes.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (75, "141_Sistine Chapel ceiling and altar wall frescoes.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (75, "142_Sistine Chapel ceiling and altar wall frescoes.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (75, "143_Sistine Chapel ceiling and altar wall frescoes.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (75, "144_Sistine Chapel ceiling and altar wall frescoes.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (76, "145_School of Athens.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (77, "146_Isenheim altarpiece.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (77, "147_Isenheim altarpiece.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (78, "148_Entombment of Christ.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (79, "149_Allegory of Law and Grace.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (80, "150_Venus of Urbino.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (81, "151_Frontispiece of the Codex Mendoza.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (82, "152_Il Gesù, including Triumph of the Name of Jesus ceiling fresco.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (82, "153_Il Gesù, including Triumph of the Name of Jesus ceiling fresco.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (82, "154_Il Gesù, including Triumph of the Name of Jesus ceiling fresco.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (83, "155_Hunters in the Snow.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (84, "156_Mosque of Selim II.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (84, "157_Mosque of Selim II.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (84, "158_Mosque of Selim II.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (85, "159_Calling of Saint Matthew.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (86, "160_Henri IV Receives the Portrait of Marie de’ Medici, from the Marie de’ Medici Cycle.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (87, "161_Self-Portrait with Saskia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (88, "162_San Carlo alle Quattro Fontane.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (88, "163_San Carlo alle Quattro Fontane.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (88, "164_San Carlo alle Quattro Fontane.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (89, "165_Ecstasy of Saint Teresa.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (89, "166_Ecstasy of Saint Teresa.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (89, "167_Ecstasy of Saint Teresa.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (90, "168_Angel with Arquebus, Asiel Timor Dei.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (91, "169_Las Meninas.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (92, "170_Woman Holding a Balance.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (93, "171_The Palace at Versailles.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (93, "172_The Palace at Versailles.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (93, "173_The Palace at Versailles.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (93, "174_The Palace at Versailles.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (93, "175_The Palace at Versailles.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (94, "176_Screen with the Siege of Belgrade and hunting scene.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (94, "177_Screen with the Siege of Belgrade and hunting scene.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (95, "178_The Virgin of Guadalupe (Virgen de Guadalupe).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (96, "179_Fruit and Insects.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (97, "180_Spaniard and Indian Produce a Mestizo.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (98, "181_The Tête à Tête, from Marriage à la Mode.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (99, "182_Portrait of Sor Juana Inés de la Cruz.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (100, "183_A Philosopher Giving a Lecture on the Orrery.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (101, "184_The Swing.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (102, "185_Monticello.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (102, "186_Monticello.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (103, "187_The Oath of the Horatii.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (104, "188_George Washington.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (105, "189_Self-Portrait.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (106, "190_Y no hai remedio (And There’s Nothing to Be Done), from Los Desastres de la Guerra (The Disasters of War), plate 15.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (107, "191_La Grande Odalisque.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (108, "192_Liberty Leading the People.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (109, "193_The Oxbow (View from Mount Holyoke, Northampton, Massachusetts, after a Thunderstorm).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (110, "194_Still Life in Studio.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (111, "195_Slave Ship (Slavers Throwing Overboard the Dead and Dying, Typhoon Coming On).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (112, "196_Palace of Westminster (Houses of Parliament).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (112, "197_Palace of Westminster (Houses of Parliament).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (112, "198_Palace of Westminster (Houses of Parliament).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (113, "199_The Stone Breakers.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (114, "200_Nadar Raising Photography to the Height of Art.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (115, "201_Olympia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (116, "202_The Saint-Lazare Station.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (117, "203_The Horse in Motion.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (118, "204_The Valley of Mexico from the Hillside of Santa Isabel (El Valle de México desde el Cerro de Santa Isabel).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (119, "205_The Burghers of Calais.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (120, "206_The Starry Night.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (121, "207_The Coiffure.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (122, "208_The Scream.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (123, "209_Where Do We Come From_ What Are We_ Where Are We Going_.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (124, "210_Carson, Pirie, Scott and Company Building.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (124, "211_Carson, Pirie, Scott and Company Building.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (124, "212_Carson, Pirie, Scott and Company Building.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (125, "213_Mont Sainte-Victoire.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (126, "214_Les Demoiselles d’Avignon.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (127, "215_The Steerage.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (128, "216_The Kiss.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (129, "217_The Kiss.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (130, "218_The Portuguese.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (131, "219_Goldfish.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (132, "220_Improvisation 28 (second version).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (133, "221_Self-Portrait as a Soldier.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (134, "222_Memorial Sheet for Karl Liebknecht.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (135, "223_Villa Savoye.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (135, "224_Villa Savoye.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (136, "225_Composition with Red, Blue and Yellow.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (137, "226_Illustration from The Results of the First Five-Year Plan.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (138, "227_Object (Le Déjeuner en fourrure).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (139, "228_Fallingwater.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (139, "229_Fallingwater.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (139, "230_Fallingwater.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (140, "231_The Two Fridas.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (141, "232_The Migration of the Negro, Panel no. 49.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (142, "233_The Jungle.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (143, "234_Dream of a Sunday Afternoon in the Alameda Park.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (144, "235_Fountain (second version).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (145, "236_Woman, I.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (146, "237_Seagram Building.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (147, "238_Marilyn Diptych.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (148, "239_Narcissus Garden.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (149, "240_The Bay.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (150, "241_Lipstick (Ascending) on Caterpillar Tracks.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (151, "242_Spiral Jetty.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (152, "243_House in New Castle County.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (152, "244_House in New Castle County.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (153, "245_Chavín de Huántar.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (153, "246_Chavín de Huántar.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (153, "247_Chavín de Huántar.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (153, "248_Chavín de Huántar.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (154, "249_Mesa Verde cliff dwellings.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (155, "250_Yaxchilán.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (155, "251_Yaxchilán.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (155, "252_Yaxchilán.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (156, "253_Great Serpent Mound.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (157, "254_Templo Mayor (Main Temple).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (157, "255_Templo Mayor (Main Temple).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (157, "256_Templo Mayor (Main Temple).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (157, "257_Templo Mayor (Main Temple).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (158, "258_Ruler’s feather headdress (probably of Motecuhzoma II).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (159, "259_City of Cusco, including Qorikancha (Inka main temple), Santo Domingo (Spanish colonial convent), and Walls at Saqsa Waman (Sacsayhuaman).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (159, "260_City of Cusco, including Qorikancha (Inka main temple), Santo Domingo (Spanish colonial convent), and Walls at Saqsa Waman (Sacsayhuaman).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (159, "261_City of Cusco, including Qorikancha (Inka main temple), Santo Domingo (Spanish colonial convent), and Walls at Saqsa Waman (Sacsayhuaman).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (160, "262_Maize cobs.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (161, "263_City of Machu Picchu.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (161, "264_City of Machu Picchu.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (161, "265_City of Machu Picchu.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (162, "266_All-T’oqapu tunic.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (163, "267_Bandolier bag.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (164, "268_Transformation mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (164, "269_Transformation mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (165, "270_Painted elk hide.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (166, "271_Black-on-black ceramic vessel.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (167, "272_Conical tower and circular wall of Great Zimbabwe.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (167, "273_Conical tower and circular wall of Great Zimbabwe.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (168, "274_Great Mosque of Djenné.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (168, "275_Great Mosque of Djenné.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (169, "276_Wall plaque, from Oba’s palace.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (169, "277_Wall plaque, from Oba’s palace.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (170, "278_Sika dwa kofi (Golden Stool).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (170, "279_Sika dwa kofi (Golden Stool).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (171, "280_Ndop (portrait figure) of King Mishe miShyaang maMbul.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (171, "281_Ndop (portrait figure) of King Mishe miShyaang maMbul.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (172, "282_Power figure (Nkisi n’kondi ).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (173, "283_Female (Pwo) mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (173, "284_Female (Pwo) mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (174, "285_Portrait mask (Mblo).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (174, "286_Portrait mask (Mblo).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (175, "287_Bundu mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (175, "288_Bundu mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (176, "289_Ikenga (shrine figure).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (177, "290_Lukasa (memory board).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (177, "291_Lukasa (memory board).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (178, "292_Aka elephant mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (178, "293_Aka elephant mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (179, "294_Reliquary figure (byeri).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (180, "295_Veranda post of enthroned king and senior wife (Opo Ogoga).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (181, "296_Petra, Jordan_ Treasury and Great Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (181, "297_Petra, Jordan_ Treasury and Great Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (181, "298_Petra, Jordan_ Treasury and Great Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (182, "299_Buddha.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (182, "300_Buddha.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (183, "301_The Kaaba.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (183, "302_The Kaaba.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (184, "303_Jowo Rinpoche, enshrined in the Jokhang Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (185, "304_Dome of the Rock.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (185, "305_Dome of the Rock.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "308_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "309_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "310_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "311_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "312_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "313_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "314_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (186, "315_Great Mosque (Masjid-e Jameh).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (187, "316_Folio from a Qur’an.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (188, "317_Basin (Baptistère de St. Louis).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (189, "318_Bahram Gur Fights the Karg, folio from the Great Il-Khanid Shahnama.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (190, "319_The Court of Gayumars, folio from Shah Tahmasp’s Shahnama.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (191, "320_The Ardabil Carpet.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (192, "321_Great Stupa at Sanchi.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (192, "322_Great Stupa at Sanchi.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (192, "323_Great Stupa at Sanchi.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (193, "324_Terra cotta warriors from mausoleum of the first Qin emperor of China.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (193, "325_Terra cotta warriors from mausoleum of the first Qin emperor of China.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (194, "326_Funeral banner of Lady Dai (Xin Zhui).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (195, "327_Longmen Caves.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (195, "328_Longmen Caves.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (195, "329_Longmen Caves.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (196, "330_Gold and jade crown.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (197, "331_Todai-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (197, "332_Todai-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (197, "333_Todai-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (197, "334_Todai-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (197, "335_Todai-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (198, "336_Borobudur Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (198, "337_Borobudur Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (198, "338_Borobudur Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (199, "339_Angkor, the temple of Angkor Wat and the city of Angkor Thom, Cambodia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (199, "340_Angkor, the temple of Angkor Wat and the city of Angkor Thom, Cambodia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (199, "341_Angkor, the temple of Angkor Wat and the city of Angkor Thom, Cambodia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (199, "342_Angkor, the temple of Angkor Wat and the city of Angkor Thom, Cambodia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (199, "343_Angkor, the temple of Angkor Wat and the city of Angkor Thom, Cambodia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (199, "344_Angkor, the temple of Angkor Wat and the city of Angkor Thom, Cambodia.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (200, "345_Lakshmana Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (200, "346_Lakshmana Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (200, "347_Lakshmana Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (200, "348_Lakshmana Temple.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (201, "349_Travelers among Mountains and Streams.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (202, "350_Shiva as Lord of Dance (Nataraja).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (203, "351_Night Attack on the Sanjô Palace.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (203, "352_Night Attack on the Sanjô Palace.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (204, "353_The David Vases.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (205, "354_Portrait of Sun Sukju (1417-1475).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (206, "355_Forbidden City.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (206, "356_Forbidden City.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (206, "357_Forbidden City.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (206, "358_Forbidden City.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (206, "359_Forbidden City.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (207, "360_Ryoan-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (207, "361_Ryoan-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (207, "362_Ryoan-ji.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (208, "363_Jahangir Preferring a Sufi Shaikh to Kings.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (209, "364_Taj Mahal.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (209, "365_Taj Mahal.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (210, "366_White and Red Plum Blossoms.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (211, "367_Under the Wave off Kanagawa (Kanagawa oki nami ura), also known as the Great Wave, from the series Thirty-Six Views of Mount Fuji..png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (212, "368_Chairman Mao en Route to Anyuan.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (213, "369_Nan Madol.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (213, "370_Nan Madol.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (214, "371_Moai on platform (ahu).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (215, "372_Ahu ‘ula (feather cape).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (216, "373_Staff god.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (216, "374_Staff god.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (216, "375_Staff god.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (217, "376_Female deity.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (217, "377_Female deity.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (218, "378_Buk (mask).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (219, "379_Hiapo (tapa).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (220, "380_Tamati Waka Nene.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (221, "381_Navigation chart.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (222, "382_Malagan display and mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (222, "383_Malagan display and mask.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (223, "384_Presentation  of Fijian mats and tapa cloths to Queen Elizabeth II.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (224, "385_The Gates.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (224, "386_The Gates.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (225, "387_Vietnam Veterans Memorial.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (225, "388_Vietnam Veterans Memorial.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (226, "389_Horn Players.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (227, "390_Summer Trees.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (228, "391_Androgyne III.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (229, "392_A Book from the Sky.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (230, "393_Pink Panther.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (231, "394_Untitled (228) Cindy Sherman.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (232, "395_Dancing at the Louvre, from the series The French Collection, Part I.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (233, "396_Trade (Gifts for Trading Land with White People).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (234, "397_Earth’s Creation.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (235, "398_Rebellious Silence, from the Women of Allah series.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (236, "399_En la Barberia no se Llora (No Crying Allowed in the Barbershop).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (237, "400_Pisupo Lua Afe (Corned Beef 2000).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (238, "401_Electronic Superhighway.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (239, "402_The Crossing.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (240, "403_Guggenheim Museum Bilbao.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (240, "404_Guggenheim Museum Bilbao.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (240, "405_Guggenheim Museum Bilbao.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (241, "406_Pure Land.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (242, "407_Lying with the Wolf.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (243, "408_Darkytown Rebellion.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (244, "409_The Swing (after Fragonard).png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (245, "410_Old Man’s Cloth.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (246, "411_Stadia II.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (247, "412_Preying Mantra.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (248, "413_Shibboleth.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (249, "414_MAXXI National Museum of XXI Century Arts.png")`);
        db.run(`INSERT OR IGNORE INTO Images (id, image) VALUES (250, "415_Kui Hua Zi (Sunflower Seeds).png")`);
    })
}

module.exports = {initializeImages};